### ISSUE TITLE
Issue sh: -c: line 1: syntax error: unexpected end of file

### ISSUE THREAD

**Issue by nadtoka** [J3-Tech/Youtube-dl-php#6]
We made a plugin that uses your library to download  videos from youtube vut suddely got this error.... and this looks like some bug in code. Can you assist please and direct us to the right way ? we really need it to be fixed. 

It looks like some quotes are missin for $process value... 

2016/06/16 00:14:09 [error] 3963#0: *182310768 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'Youtubedl\Exceptions\YoutubedlException' with message 'sh: -c: line 0: unexpected EOF while looking for matching ``'
sh: -c: line 1: syntax error: unexpected end of file
' in /var/www/site.com/http/wp-content/plugins/yt-downloader/vendor/labzone/youtube-downloader/src/Youtubedl/Youtubedl.php:73
Stack trace:
#0 /var/www/site.comhttp/wp-content/plugins/yt-downloader/yt-downloader.php(204): Youtubedl\Youtubedl->execute()
#1 [internal function]: download_youtube_video('')
#2 /var/www/site.com/http/wp-includes/plugin.php(525): call_user_func_array('download_youtub...', Array)
#3 /var/www/site.com/http/wp-admin/admin-ajax.php(89): do_action('wp_ajax_downloa...')
#4 {main}

  thrown in /var/www/site.com/http/wp-content/plugins/yt-downloader/vendor/labzone/youtube-downloader/src/Youtubedl/Youtubedl.php on line 73"

**Comment by nadtoka** [comment]
solved
